#!/bin/bash -l
# author: Lucas Patel (lpatel@ucsd.edu)
# date: 12/22/23 
# description: Script to perform index-based host filtration on FASTQ files from metagenomics experiments by assessing PML distributions generated by Movi to distinguish human from non-human reads.

source config.sh
conda activate human-depletion

f=$1
basename=$(basename "$f" .fastq)

# Check if .bin file exists before running MOVI query
if [ ! -f "$f.default.mpml.bin" ]; then
  echo "$MOVI_PATH query $MOVI_INDEX_PATH $f"
  eval "$MOVI_PATH query $MOVI_INDEX_PATH $f"
else
  echo "Skipping MOVI query: $f.default.mpml.bin already exists."
fi

# Check if .mpml.txt file exists before converting PMLs
if [ ! -f "$f.mpml.txt" ]; then
  eval "$MOVI_PATH view $f.default.mpml.bin > $f.mpml.txt"
else
  echo "Skipping MOVI view: $f.mpml.txt already exists."
fi

python scripts/filter_pmls.py $f.mpml.txt $f $TMPDIR

# Check if new .fastq files exist
if [ ! -f "$TMPDIR/${basename}.fastq.mpml.non-human.fastq" ]; then
  echo "Error: $TMPDIR/${basename}.fastq.mpml.non-human.fastq does not exist."
  exit 1
fi

mv "$TMPDIR/${basename}.fastq.mpml.non-human.fastq" "$TMPDIR/${basename}.HPRC-INDEX.fastq"
